version: '3.8'
services:
  frontend:
    image: jonathan31amaral/RentalCompany-frontend
    ports:
      - "4200:80"
    networks:
      - RentalCompany-network

  backend:
    image: jonathan31amaral/RentalCompany-api
    ports:
      - "5099:80"
    restart: always
    networks:
      - RentalCompany-network
    environment:
      DB_CONNECTION_STRING: "Host=database;Port=5432;Database=RentalCompanyDb;Username=postgres;Password=postgrespw"

  database:
    image: postgres:14
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespw"
      POSTGRES_DB: "RentalCompanyDb"
    networks:
      - RentalCompany-network

networks:
  RentalCompany-network:
    driver: bridge
