apiVersion: v1
kind: Pod
metadata:
  name: RentalCompany-api
  labels:
    app: RentalCompany-api
spec:
  containers:
    - name: RentalCompany-api
      image: jonathan31amaral/RentalCompany-api
      ports:
        - containerPort: 80
      env:
      - name: DB_CONNECTION_STRING
        value: "Host=svc-database;Port=5432;Database=RentalCompanyDb;Username=postgres;Password=postgrespw"
    