apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: RentalCompany-api-replicaset
spec:
  template: 
    metadata:
      name: RentalCompany-api
      labels:
        app: RentalCompany-api
    spec:
      containers:
        - name: RentalCompany-api-container
          image: jonathan31amaral/RentalCompany-api
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: RentalCompany-api