# NodePort expoem para o mundo o node
apiVersion: v1
kind: Service
metadata:
  name: svc-RentalCompany-api
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: RentalCompany-api